const ActionTypes = {
  ADD_MEMBER: "ADD_MEMBER",
  DELETE_MEMBER: "DELETE_MEMBER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  USER_REQUEST: "USER_REQUEST",
  LOG_OUT: "LOG_OUT",
  LOAD_PROFILE: "LOAD_PROFILE",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_BY_EMAIL_SUCCESS: "LOGIN_BY_EMAIL_SUCCESS",
  LOGIN_BY_EMAIL_FAIL: "LOGIN_BY_EMAIL_FAIL",
};

export default ActionTypes;
