const ActionTypes = {
  ADD_MEMBER: "ADD_MEMBER",
  DELETE_MEMBER: "DELETE_MEMBER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOG_OUT: "LOG_OUT",
  LOAD_PROFILE: "LOAD_PROFILE",
};

export default ActionTypes;
